import { StrictMode, startTransition } from "react";
import { hydrateRoot } from "react-dom/client";
import {
  createBrowserRouter,
  RouterProvider,
  createClientRoutes,
} from "react-router";
// This is generated by @react-router/dev at build time
import * as routeModules from "virtual:react-router";

const routes = createClientRoutes(routeModules.routes);

const router = createBrowserRouter(routes, {
  basename: "/athlio-code", // same as your Vite base
});

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <RouterProvider router={router} />
    </StrictMode>,
  );
});
